name: "Azure Integration Tests"

# These tests provision resources on Faasm's Azure subscription to run
# integration tests on a production environment. To limit the cost of running
# them, we only trigger them on workflow dispatch. In order to run them, you
# need to navigate to the Actions tab on GitHub, and click the run button
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  aks:
    runs-on: self-hosted
    env:
      CLUSTER_NAME_BASE: gha-cluster
    strategy:
      fail-fast: true
      # Running two Kubernetes clusters side-by-side from the same user in the
      # same machine creates conflicts in the local .kubeconfig file. A
      # possible fix would be to use one .kubeconfig file per cluster, and make
      # all k8s commands point to that .kubeconfig file. Given that this
      # workflow is not latency-sensitive, we actually don't mind that jobs are
      # run one after the other, so we don't implement the fix.
      max-parallel: 1
      matrix:
        sgx: [True, False]
    steps:
      - name: "Check out the experiment-base code"
        uses: actions/checkout@v3
        with:
          repository: faasm/experiment-base
      - name: "Start a managed k8s cluster on Azure's Kubernetes Service"
        # TODO: deploy with a different name (as a parameter) and allow --sgx=False
        # TODO: consider using a special path for `.kubeconfig`
        run: ./bin/inv_wrapper.sh \
          cluster.provision --vm Standard_DC4s_v3 --nodes 4 --location eastus2 --sgx \
          cluster.credentials
